version: "3.9"

services:
  controle-tccs-api:
    build: ./controle-tccs-api
    container_name: controle-tccs-api-hom
    image: controle-tccs-api-hom:latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - controle-tccs-api/.env
    networks:
      - tccs-tst-net

  controle-tccs-front:
    build: ./controle-tccs-front
    container_name: controle-tccs-front-hom
    image: controle-tccs-front-hom:latest
    ports:
      - "5000:80"
    restart: unless-stopped
    env_file:
      - controle-tccs-front/.env
    depends_on:
      - controle-tccs-api
    networks:
      - tccs-tst-net

networks:
  tccs-tst-net:
    driver: bridge
    ipam:
       config:
        - subnet: 172.30.102.0/24